// js/data.js - Trendify Product Data

const TrendifyData = {
  // All products
  products: [
    // 👕 Men (6)
    {
      id: 1,
      name: "Slim Fit Casual Shirt",
      price: 899,
      category: "men",
      image: "../assets/products/men/product-men-1.jpg",
      description: "Stylish cotton shirt with modern slim fit design.",
      stock: 50,
      featured: true,
    },
    {
      id: 2,
      name: "Men's Denim Jacket",
      price: 1499,
      category: "men",
      image: "../assets/products/men/product-men-2.jpg",
      description: "Classic blue denim jacket for casual wear.",
      stock: 30,
      featured: true,
    },
    {
      id: 3,
      name: "Formal Office Shirt",
      price: 799,
      category: "men",
      image: "../assets/products/men/product-men-3.jpg",
      description: "Premium formal shirt for office and meetings.",
      stock: 40,
      featured: false,
    },
    {
      id: 4,
      name: "Men's Cotton Trousers",
      price: 699,
      category: "men",
      image: "../assets/products/men/product-men-4.jpg",
      description: "Comfortable cotton trousers for daily wear.",
      stock: 60,
      featured: false,
    },
    {
      id: 5,
      name: "Men's Leather Belt",
      price: 599,
      category: "accessories",
      image: "../assets/products/men/product-men-5.jpg",
      description: "Genuine leather belt with metallic buckle.",
      stock: 100,
      featured: true,
    },
    {
      id: 6,
      name: "Men's Sports Shoes",
      price: 1299,
      category: "footwear",
      image: "../assets/products/men/product-men-6.jpg",
      description: "Lightweight running shoes with shock absorption.",
      stock: 45,
      featured: true,
    },

    // 👗 Women (6)
    {
      id: 7,
      name: "Women's Floral Dress",
      price: 1199,
      category: "women",
      image: "../assets/products/women/product-women-1.jpg",
      description: "Elegant floral dress for parties and events.",
      stock: 35,
      featured: true,
    },
    {
      id: 8,
      name: "Women's Denim Jeans",
      price: 999,
      category: "women",
      image: "../assets/products/women/product-women-2.jpg",
      description: "Skinny fit jeans with stretchable fabric.",
      stock: 55,
      featured: true,
    },
    {
      id: 9,
      name: "Women's Winter Coat",
      price: 1899,
      category: "women",
      image: "../assets/products/women/product-women-3.jpg",
      description: "Warm winter coat with hood and pockets.",
      stock: 25,
      featured: false,
    },
    {
      id: 10,
      name: "Women's Handbag",
      price: 799,
      category: "accessories",
      image: "../assets/products/women/product-women-4.jpg",
      description: "Stylish handbag with multiple compartments.",
      stock: 70,
      featured: true,
    },
    {
      id: 11,
      name: "Women's High Heels",
      price: 1399,
      category: "footwear",
      image: "../assets/products/women/product-women-5.jpg",
      description: "Comfortable high heels for formal occasions.",
      stock: 40,
      featured: false,
    },
    {
      id: 12,
      name: "Women's Cotton Saree",
      price: 1599,
      category: "women",
      image: "../assets/products/women/product-women-6.jpg",
      description: "Traditional cotton saree with beautiful print.",
      stock: 30,
      featured: true,
    },

    // 💎 Accessories (6)
    {
      id: 13,
      name: "Leather Wallet",
      price: 599,
      category: "accessories",
      image: "../assets/products/accessories/product-accessory-1.jpg",
      description: "Genuine leather wallet with RFID protection.",
      stock: 100,
      featured: false,
    },
    {
      id: 14,
      name: "Sunglasses",
      price: 499,
      category: "accessories",
      image: "../assets/products/accessories/product-accessory-2.jpg",
      description: "UV protected sunglasses with UV400 lens.",
      stock: 80,
      featured: true,
    },
    {
      id: 15,
      name: "Smart Watch",
      price: 2499,
      category: "electronics",
      image: "../assets/products/electronics/product-electronics-8.jpg",
      description: "Fitness tracker with heart rate monitor.",
      stock: 25,
      featured: true,
    },
    {
      id: 16,
      name: "Bluetooth Earphones",
      price: 899,
      category: "electronics",
      image: "../assets/products/electronics/product-electronics-7.jpg",
      description: "Wireless earbuds with 20hr battery life.",
      stock: 60,
      featured: true,
    },
    {
      id: 17,
      name: "Men's Cap",
      price: 399,
      category: "accessories",
      image: "../assets/products/accessories/product-accessory-5.jpg",
      description: "Cotton cap for sunny days.",
      stock: 90,
      featured: false,
    },
    {
      id: 18,
      name: "Women's Necklace",
      price: 749,
      category: "accessories",
      image: "../assets/products/accessories/product-accessory-6.jpg",
      description: "Silver necklace with pendant.",
      stock: 45,
      featured: true,
    },

    // 👟 Footwear (6)
    {
      id: 19,
      name: "Casual Sneakers",
      price: 1099,
      category: "footwear",
      image: "../assets/products/footware/product-footwear-1.jpg",
      description: "Comfortable sneakers for everyday use.",
      stock: 50,
      featured: true,
    },
    {
      id: 20,
      name: "Sports Running Shoes",
      price: 1599,
      category: "footwear",
      image: "../assets/products/footware/product-footwear-2.jpg",
      description: "Breathable running shoes with grip sole.",
      stock: 35,
      featured: true,
    },
    {
      id: 21,
      name: "Men's Formal Shoes",
      price: 1399,
      category: "footwear",
      image: "../assets/products/footware/product-footwear-3.jpg",
      description: "Leather formal shoes for office wear.",
      stock: 40,
      featured: false,
    },
    {
      id: 22,
      name: "Women's Sandals",
      price: 699,
      category: "footwear",
      image: "../assets/products/women/product-footwear-4.jpg",
      description: "Comfortable sandals for summer.",
      stock: 70,
      featured: true,
    },
    {
      id: 23,
      name: "Kids' School Shoes",
      price: 599,
      category: "footwear",
      image: "../assets/products/footware/product-footwear-5.jpg",
      description: "Durable school shoes for kids.",
      stock: 80,
      featured: false,
    },
    {
      id: 24,
      name: "Slippers",
      price: 299,
      category: "footwear",
      image: "../assets/products/footware/product-footwear-6.jpg",
      description: "Soft slippers for home use.",
      stock: 120,
      featured: false,
    },

    // 📱 Electronics (6)
    {
      id: 25,
      name: "Wired Earphones",
      price: 1299,
      category: "electronics",
      image: "../assets/products/electronics/product-electronics-1.jpg",
      description: "Tangle-free wired earphones with 3.5mm jack and deep bass.",
      stock: 60,
      featured: true,
    },
    {
      id: 26,
      name: "Power Bank 10000mAh",
      price: 999,
      category: "electronics",
      image: "../assets/products/electronics/product-electronics-2.jpg",
      description: "Fast charging power bank with dual USB ports.",
      stock: 75,
      featured: true,
    },
    {
      id: 27,
      name: "Smart LED Bulb",
      price: 499,
      category: "electronics",
      image: "../assets/products/electronics/product-electronics-3.jpg",
      description: "WiFi enabled color changing LED bulb.",
      stock: 50,
      featured: false,
    },
    {
      id: 28,
      name: "USB Type-C Cable",
      price: 199,
      category: "electronics",
      image: "../assets/products/electronics/product-electronics-4.jpg",
      description: "3A fast charging cable, 1.5m long.",
      stock: 200,
      featured: false,
    },
    {
      id: 29,
      name: "Bluetooth Speaker",
      price: 1499,
      category: "electronics",
      image: "../assets/products/electronics/product-electronics-5.jpg",
      description: "Portable speaker with 12hr playback.",
      stock: 30,
      featured: true,
    },
    {
      id: 30,
      name: "Laptop Cooling Pad",
      price: 799,
      category: "electronics",
      image: "../assets/products/electronics/product-electronics-6.jpg",
      description: "RGB cooling pad with 3 fans.",
      stock: 45,
      featured: false,
    },
  ],

  // Get product by ID
  getProduct: function (id) {
    return this.products.find((p) => p.id === id);
  },

  // Get products by category
  getProductsByCategory: function (category) {
    return this.products.filter((p) => p.category === category);
  },
};
